; -- 国际化翻译 --
; 注意: 此文件通过自定义函数[parse_ini()]加载, 仅仅过滤首行`#`和`;`, 内容无需用引号包含
; 示例: name = 名称
Host = 主机
Template = 模板

disabled = 已禁用
enabled = 已启用
not supported = 不支持
problem = 问题
ok = 正常

Number of hosts = 主机数量
Number of items = 监控项数量
Number of triggers = 触发器数量
Number of templates = 模板数量

Perseus Server = 采集服务器
Version = 版本
Required server performance, new values per second = 每秒新值
execute Success = 执行成功

The user does not have any media configured = 用户未配置任何媒介
The user does not configure the {media} account = 该用户未配置{media}账号
State Setting = 状态配置

Perseus server = 采集服务器
Perseus agent = Perseus 客户端
Perseus trapper = Perseus采集器
Simple check = 简单检查
Perseus internal = Perseus内部
Perseus agent (active) = Perseus客户端(主动式)
Perseus aggregate = Perseus整合
Web item = Web item
External check = 外部检查
Database monitor = 数据库监控
IPMI agent = IPMI客户端
SSH agent = SSH客户端
TELNET agent = TELNET客户端
Calculated = 计算的
JMX agent = JMX客户端
SNMP trap = SNMP采集
SNMP agent = SNMP代理
Dependent item = 相关项目
HTTP agent = HTTP 代理
Calculated = 可计算的
