; Zapi异常码 60750001~60759999
; 注意, 若配置值出现特殊符号, 避免内容异常, 需要把内容引号包起来
; 示例: 60750001 = '[{name}] is a title'
60750601 = 'Failed to create auto discovery rule'
60750602 = 'Failed to update auto discovery rule'
60750603 = 'Failed to delete auto discovery rule'
