; Zapi异常码 60750001~60759999
; 注意, 若配置值出现特殊符号, 避免内容异常, 需要把内容引号包起来
; 示例: 60750001 = '[{name}] is a title'
60750201 = 'Invalid parameter: {error}'
60750202 = 'Check the key, please. Default example was passed.'
60750203 = 'No permissions to referred object or it does not exist!'
60750204 = 'Create Item failed!'
60750205 = 'Update Item failed!'
60750206 = 'Delete Item failed!'
