; Zapi异常码 60750001~60759999
; 注意, 若配置值出现特殊符号, 避免内容异常, 需要把内容引号包起来
; 示例: 60750001 = '[{name}] is a title'
60750701 = 'Create Proxy failed!'
60750702 = 'Update Proxy failed!'
60750703 = 'Delete Proxy failed!'

