; Zapi异常码 60750001~60759999
; 注意, 若配置值出现特殊符号, 避免内容异常, 需要把内容引号包起来
; 示例: 60750001 = '[{name}] is a title'
60750801 = 'Failed to create regular expression'
60750802 = 'Failed to update regular expression'
60750803 = 'Failed to delete regular expression'

