; Zapi异常码 60750001~60759999
; 注意, 若配置值出现特殊符号, 避免内容异常, 需要把内容引号包起来
; 示例: 60750001 = '[{name}] is a title'
60750301 = 'Create trigger failed'
60750302 = 'Update trigger failed'
60750303 = 'Delete trigger failed'
60750304 = 'Cannot insert trigger expression'
