; Zapi异常码 60750001~60759999
; 注意, 若配置值出现特殊符号, 避免内容异常, 需要把内容引号包起来
; 示例: 60750001 = '[{name}] is a title'

60750001 = 'Invalid parameter {attribute}: {error}'
60750002 = 'Deprecated parameter "{attribute}" cannot be used with "{parameter}".'
60750003 = 'Invalid parameter: {error}'
60750004 = 'No permissions to referred object or it does not exist!'

