#發布時間
release_time = 2025-09-04

#添加某些功能
[feature]
1 = 【帕爾修斯】主機列表：手動安裝Agent抽屜頁支援自訂新增多個curl地址。
2 = 【帕爾修斯】主機管理：自動發現規則新增頁抽屜新增【立即執行】功能
3 = 【帕爾修斯】模板管理：模板導入適配導入yaml格式的模板

#修復某些Bug
[fix]
1 = 【帕爾修斯】主機管理：啟用禁用不生效
2 = 【帕爾修斯】模板管理：未創建的監控項，進行測試提示缺少itemid
3 = 【帕爾修斯】主機管理：測試裡面的proxy沒取代理的名稱
4 = 【帕爾修斯】主機列表：非超管用戶，沒有監控模組時，訪問主機管理，報無權限提示
