#發布時間
release_time = 2025-09-19

#添加某些功能
[feature]
1 =【帕爾修斯】主機列表：列表新增業務名稱欄位，支援點擊跳轉至設備需求頁。
2 =【帕爾修斯】全域：新增全域欄位設定功能。
3 =【帕爾修斯】主機和模版管理：監控項、觸發器、自動發現等功能新增編輯、新增、刪除的選單權限。

#修復某些Bug
[fix]
1 =【帕爾修斯】模版管理：修復TrueNAS模版匯入失敗，因預處理為巨集值無法匯入。
