#發布時間
release_time = 2025-11-06

#添加某些功能
[feature]
1 =【帕爾修斯】主機管理：監控項新增批次執行功能。
2 =【帕爾修斯】主機管理：新增編輯主機時，支援新增繼承巨集功能。
3 =【帕爾修斯】模板管理：監控項列表新增批次更新功能。
4 =【帕爾修斯】模板管理：監控項新增支援選擇自定義時間間隔。
5 =【帕爾修斯】模板管理：模板管理列表新增克隆功能。
6 =【帕爾修斯】模板/主機管理：監控項列表新增告警搜尋功能。
7 =【帕爾修斯】模板/主機管理：新增觸發器時，新增添加運算式功能。
8 =【帕爾修斯】模板/主機管理：監控項、監控項原型、觸發器、觸發器原型新增克隆功能。
9 =【帕爾修斯】憑證管理：憑證管理新增匯入功能，支援單條規則多個SSH帳密或SNMP社群名稱匯入。
10 =【帕爾修斯】發現管理：掃描清單功能優化並新增掃描失敗清單。

#修復某些Bug
[fix]
1 =【帕爾修斯】模板管理：切換監控項類型會清空指標分類資料的問題。
