<?php

return [
    'key' => 'configid',
    'fields' => [
        'configid' => [
            'null' => false,
            'type' => 'id',
            'length' => 20,
        ],
        'work_period' => [
            'null' => false,
            'type' => 'char',
            'length' => 255,
            'default' => '1-5,09:00-18:00',
        ],
        'alert_usrgrpid' => [
            'null' => true,
            'type' => 'id',
            'length' => 20,
            'ref_table' => 'usrgrp',
            'ref_field' => 'usrgrpid',
        ],
        'default_theme' => [
            'null' => false,
            'type' => 'char',
            'length' => 128,
            'default' => 'blue-theme',
        ],
        'authentication_type' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '0',
        ],
        'discovery_groupid' => [
            'null' => true,
            'type' => 'id',
            'length' => 20,
            'ref_table' => 'hstgrp',
            'ref_field' => 'groupid',
        ],
        'max_in_table' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '50',
        ],
        'search_limit' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '1000',
        ],
        'severity_color_0' => [
            'null' => false,
            'type' => 'char',
            'length' => 6,
            'default' => '97AAB3',
        ],
        'severity_color_1' => [
            'null' => false,
            'type' => 'char',
            'length' => 6,
            'default' => '7499FF',
        ],
        'severity_color_2' => [
            'null' => false,
            'type' => 'char',
            'length' => 6,
            'default' => 'FFC859',
        ],
        'severity_color_3' => [
            'null' => false,
            'type' => 'char',
            'length' => 6,
            'default' => 'FFA059',
        ],
        'severity_color_4' => [
            'null' => false,
            'type' => 'char',
            'length' => 6,
            'default' => 'E97659',
        ],
        'severity_color_5' => [
            'null' => false,
            'type' => 'char',
            'length' => 6,
            'default' => 'E45959',
        ],
        'severity_name_0' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => 'Not classified',
        ],
        'severity_name_1' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => 'Information',
        ],
        'severity_name_2' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => 'Warning',
        ],
        'severity_name_3' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => 'Average',
        ],
        'severity_name_4' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => 'High',
        ],
        'severity_name_5' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => 'Disaster',
        ],
        'ok_period' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '5m',
        ],
        'blink_period' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '2m',
        ],
        'problem_unack_color' => [
            'null' => false,
            'type' => 'char',
            'length' => 6,
            'default' => 'CC0000',
        ],
        'problem_ack_color' => [
            'null' => false,
            'type' => 'char',
            'length' => 6,
            'default' => 'CC0000',
        ],
        'ok_unack_color' => [
            'null' => false,
            'type' => 'char',
            'length' => 6,
            'default' => '009900',
        ],
        'ok_ack_color' => [
            'null' => false,
            'type' => 'char',
            'length' => 6,
            'default' => '009900',
        ],
        'problem_unack_style' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '1',
        ],
        'problem_ack_style' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '1',
        ],
        'ok_unack_style' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '1',
        ],
        'ok_ack_style' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '1',
        ],
        'snmptrap_logging' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '1',
        ],
        'server_check_interval' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '10',
        ],
        'hk_events_mode' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '1',
        ],
        'hk_events_trigger' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '365d',
        ],
        'hk_events_internal' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '1d',
        ],
        'hk_events_discovery' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '1d',
        ],
        'hk_events_autoreg' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '1d',
        ],
        'hk_services_mode' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '1',
        ],
        'hk_services' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '365d',
        ],
        'hk_audit_mode' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '1',
        ],
        'hk_audit' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '365d',
        ],
        'hk_sessions_mode' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '1',
        ],
        'hk_sessions' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '365d',
        ],
        'hk_history_mode' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '1',
        ],
        'hk_history_global' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '0',
        ],
        'hk_history' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '90d',
        ],
        'hk_trends_mode' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '1',
        ],
        'hk_trends_global' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '0',
        ],
        'hk_trends' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '365d',
        ],
        'default_inventory_mode' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '-1',
        ],
        'custom_color' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '0',
        ],
        'http_auth_enabled' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '0',
        ],
        'http_login_form' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '0',
        ],
        'http_strip_domains' => [
            'null' => false,
            'type' => 'char',
            'length' => 2048,
            'default' => '',
        ],
        'http_case_sensitive' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '1',
        ],
        'ldap_auth_enabled' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '0',
        ],
        'ldap_case_sensitive' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '1',
        ],
        'db_extension' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '',
        ],
        'autoreg_tls_accept' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '1',
        ],
        'compression_status' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '0',
        ],
        'compress_older' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '7d',
        ],
        'instanceid' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '',
        ],
        'saml_auth_enabled' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '0',
        ],
        'saml_case_sensitive' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '0',
        ],
        'default_lang' => [
            'null' => false,
            'type' => 'char',
            'length' => 5,
            'default' => 'en_US',
        ],
        'default_timezone' => [
            'null' => false,
            'type' => 'char',
            'length' => 50,
            'default' => 'system',
        ],
        'login_attempts' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '5',
        ],
        'login_block' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '30s',
        ],
        'show_technical_errors' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '0',
        ],
        'validate_uri_schemes' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '1',
        ],
        'uri_valid_schemes' => [
            'null' => false,
            'type' => 'char',
            'length' => 255,
            'default' => 'http,https,ftp,file,mailto,tel,ssh',
        ],
        'x_frame_options' => [
            'null' => false,
            'type' => 'char',
            'length' => 255,
            'default' => 'SAMEORIGIN',
        ],
        'iframe_sandboxing_enabled' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '1',
        ],
        'iframe_sandboxing_exceptions' => [
            'null' => false,
            'type' => 'char',
            'length' => 255,
            'default' => '',
        ],
        'max_overview_table_size' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '50',
        ],
        'history_period' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '24h',
        ],
        'period_default' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '1h',
        ],
        'max_period' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '2y',
        ],
        'socket_timeout' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '3s',
        ],
        'connect_timeout' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '3s',
        ],
        'media_type_test_timeout' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '65s',
        ],
        'script_timeout' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '60s',
        ],
        'item_test_timeout' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '60s',
        ],
        'session_key' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '',
        ],
        'url' => [
            'null' => false,
            'type' => 'char',
            'length' => 255,
            'default' => '',
        ],
        'report_test_timeout' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '60s',
        ],
        'dbversion_status' => [
            'null' => false,
            'type' => 'text',
            'default' => '',
        ],
        'hk_events_service' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '1d',
        ],
        'passwd_min_length' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '8',
        ],
        'passwd_check_rules' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '8',
        ],
        'auditlog_enabled' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '1',
        ],
        'ha_failover_delay' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '1m',
        ],
        'geomaps_tile_provider' => [
            'null' => false,
            'type' => 'char',
            'length' => 255,
            'default' => '',
        ],
        'geomaps_tile_url' => [
            'null' => false,
            'type' => 'char',
            'length' => 1024,
            'default' => '',
        ],
        'geomaps_max_zoom' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '0',
        ],
        'geomaps_attribution' => [
            'null' => false,
            'type' => 'char',
            'length' => 1024,
            'default' => '',
        ],
        'vault_provider' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '0',
        ],
        'ldap_userdirectoryid' => [
            'null' => true,
            'type' => 'id',
            'length' => 20,
            'default' => null,
            'ref_table' => 'userdirectory',
            'ref_field' => 'userdirectoryid',
        ],
        'server_status' => [
            'null' => false,
            'type' => 'text',
            'default' => '',
        ],
        'jit_provision_interval' => [
            'null' => false,
            'type' => 'char',
            'length' => 32,
            'default' => '1h',
        ],
        'saml_jit_status' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '0',
        ],
        'ldap_jit_status' => [
            'null' => false,
            'type' => 'int',
            'length' => 10,
            'default' => '0',
        ],
        'disabled_usrgrpid' => [
            'null' => true,
            'type' => 'id',
            'length' => 20,
            'default' => null,
            'ref_table' => 'usrgrp',
            'ref_field' => 'usrgrpid',
        ],
    ],
];
