; Zapi异常码 60750001~60759999
; 注意, 若配置值出现特殊符号, 避免内容异常, 需要把内容引号包起来
; 示例: 60750001 = '[{name}] is a title'
60750001 = '无效的参数 {attribute}: {error}'
60750002 = '将被弃用的参数“{attribute}”不能与“{parameter}”一起使用'
60750003 = '无效的参数: {error}'
60750004 = '没有权限引用对象或其不存在！'

