#發布時間
release_time = 2025-11-06

#添加某些功能
[feature]
1 = 【帕尔修斯】主机管理：监控项新增批量执行功能。
2 = 【帕尔修斯】主机管理：新增编辑主机时，支持增加继承宏功能
3 = 【帕尔修斯】模板管理：监控项列表新增批量更新功能
4 = 【帕尔修斯】模板管理：监控项新增支持选择自定义时间间隔
5 = 【帕尔修斯】模板管理：模板管理列表新增克隆功能
6 = 【帕尔修斯】模板/主机管理：监控项列表新增告警搜素功能
7 = 【帕尔修斯】模板/主机管理：新增触发器时，新增添加表达式功能
8 = 【帕尔修斯】模板/主机管理：监控项、监控项原型、触发器、触发器原型新增克隆功能
9 = 【帕尔修斯】凭证管理：凭证管理新增导入功能，支持单条规则多个ssh账密或SNMP团体名导入
10 = 【帕尔修斯】发现管理：扫描清单功能优化及新增扫描失败清单

#修復某些Bug
[fix]
1 =【帕尔修斯】模板管理：切换监控项类型会把指标分类数据清空