#發布時間
release_time = 2025-09-19

#添加某些功能
[feature]
1 =【帕尔修斯】主机列表：列表新增业务名称字段，支持点击跳转至设备需求页。
2 =【帕尔修斯】全局：新增全局列设置功能。
3 =【帕尔修斯】主机和模版管理：监控项、触发器、自动发现等功能新增编辑、新增、删除的菜单权限。

#修復某些Bug
[fix]
1 =【帕尔修斯】模板管理：修复TrueNAS模板导入失败，由于预处理是宏值无法导入