#发布时间
release_time = 2025-09-04

#添加某些功能
[feature]
1 = 【帕尔修斯】主机列表：手动安装Agent抽屉页支持自定义新增多个curl地址。
2 = 【帕尔修斯】主机管理：自动发现规则新增页抽屉新增【立即执行】功能
3 = 【帕尔修斯】模板管理：模板导入适配导入yaml格式的模板

#修复某些Bug
[fix]
1 = 【帕尔修斯】主机管理：启用禁用不生效
2 = 【帕尔修斯】模板管理：未创建的监控项，进行测试提示缺少itemid
3 = 【帕尔修斯】主机管理：测试里面的proxy没取代理的名称
4 = 【帕尔修斯】主机列表：非超管用户，没有监控模块时，访问主机管理，报无权限提示