; -- 國際化翻譯 --
; 註意: 此文件通過自定義函數[parse_ini()]加載, 僅僅過濾首行`#`和`;`, 內容無需用引號包含
; 示例: name = 名稱
Host = 主機
Template = 模板

disabled = 已禁用
enabled = 已啟用
not supported = 不支持
problem = 問題
ok = 正常

Number of hosts = 主機數量
Number of items = 監控項數量
Number of triggers = 觸發器數量
Number of templates = 模板數量

Perseus Server = 采集服務器
Version = 版本
Required server performance, new values per second = 每秒新值
execute Success = 執行成功

The user does not have any media configured = 用戶未配置任何媒介
The user does not configure the {media} account = 該用戶未配置{media}賬號
State Setting = 狀態配置

Perseus server = 采集服務器
Perseus agent = Perseus 客戶端
Perseus trapper = Perseus采集器
Simple check = 簡單檢查
Perseus internal = Perseus內部
Perseus agent (active) = Perseus客戶端(主動式)
Perseus aggregate = Perseus整合
Web item = Web item
External check = 外部檢查
Database monitor = 數據庫監控
IPMI agent = IPMI客戶端
SSH agent = SSH客戶端
TELNET agent = TELNET客戶端
Calculated = 計算的
JMX agent = JMX客戶端
SNMP trap = SNMP采集
SNMP agent = SNMP代理
Dependent item = 相關項目
HTTP agent = HTTP 代理
Calculated = 可計算的
