; -- 国际化翻译 --
; 注意: 此文件通过自定义函数[parse_ini()]加载, 仅仅过滤首行`#`和`;`, 内容无需用引号包含
; 示例: name = Name
Perseus采集 = Perseus采集
概况 = 概況
模板管理 = 模板管理
新增模板 = 新增模板
编辑模板 = 編輯模板
删除模板 = 刪除模板
主机管理 = 主機管理
脚本管理 = 腳本管理
常规设置 = 常規設置

; 权限
状态配置 = 狀態配置
新增主机 = 新增主機
编辑主机 = 編輯主機
代理管理 = 代理管理
新增代理 = 新增代理
编辑代理 = 編輯代理
删除代理 = 刪除代理
新增脚本 = 新增腳本
编辑脚本 = 編輯腳本
删除脚本 = 刪除腳本
删除主机 = 刪除主機
创建监控项 = 創建監控項
更新监控项 = 更新監控項
删除监控项 = 刪除監控項
创建监控项原型 = 創建監控項原型
更新监控项原型 = 更新監控項原型
删除监控项原型 = 刪除監控項原型
监控项测试 = 監控項測試
监控项执行 = 監控項執行
创建触发器 = 創建觸發器
更新触发器 = 更新觸發器
删除触发器 = 刪除觸發器
创建触发器原型 = 創建觸發器原型
更新触发器原型 = 更新觸發器原型
删除触发器原型 = 刪除觸發器原型
创建自动发现 = 創建自動發現
更新自动发现 = 更新自動發現
删除自动发现 = 刪除自動發現

