; zapi 模块菜单配置数据
; 该文件无需手动添加，
; 1、请在GUI页面`/dev/menu/index`下建立数据
; 2、执行`php bin/manager module/build-menu zapi`，即可自动生成
; 注意事项
; 1、每个菜单ID是唯一标识，模块标识+3位，该模块菜单范围6075000~6075999 (1000个)
;    例如: 若是产品级别，则是6075000，非产品级别则6075001开始递增
; 2、若菜单废弃，已经使用过的ID不可以重复使用
; 3、以下为必填属性，更多属性请查看表`lw_auth_menus`
[6075000]
id=6075000    ; 菜单ID
title='Perseus采集'    ; 菜单名称
pid=0    ; 菜单父级ID
icon='/statics/images/menus/zbx.svg'    ; 菜单图标
sort=100    ; 菜单排序
;module=zapi    ; 模块名(可不填写)。默认读取当前模块
;description=''    ; 描述内容
;flag=    ; 菜单标识，配合前端页面跨模块跳转焦点标识
;url=    ; 菜单地址，前端兼容使用(默认空)
;status=1    ; 是否启用(默认启用)，启用的菜单才会在web展示
;blank=0    ; 是否新窗口打开
;display=1    ; 是否显示(默认)，若0则表示该菜单不在前端显示
type=0    ; 类型 0-分组 1-菜单
application='app-perseus-collect'    ; 应用-前端参数
name=    ; 标识-前端参数
extra=    ; 扩展-前端参数

[6075001]
id=6075001    ; 菜单ID
title='概况'    ; 菜单名称
pid=6075000    ; 菜单父级ID
icon=''    ; 菜单图标
sort=1    ; 菜单排序
;module=zapi    ; 模块名(可不填写)。默认读取当前模块
;description=''    ; 描述内容
;flag=    ; 菜单标识，配合前端页面跨模块跳转焦点标识
;url=    ; 菜单地址，前端兼容使用(默认空)
;status=1    ; 是否启用(默认启用)，启用的菜单才会在web展示
;blank=0    ; 是否新窗口打开
;display=1    ; 是否显示(默认)，若0则表示该菜单不在前端显示
type=1    ; 类型 0-分组 1-菜单
application='app-perseus-collect'    ; 应用-前端参数
name=CollectBoard    ; 标识-前端参数
extra=    ; 扩展-前端参数

[6075002]
id=6075002    ; 菜单ID
title='模板管理'    ; 菜单名称
pid=6075000    ; 菜单父级ID
icon=''    ; 菜单图标
sort=100    ; 菜单排序
;module=zapi    ; 模块名(可不填写)。默认读取当前模块
;description=''    ; 描述内容
;flag=    ; 菜单标识，配合前端页面跨模块跳转焦点标识
;url=    ; 菜单地址，前端兼容使用(默认空)
;status=1    ; 是否启用(默认启用)，启用的菜单才会在web展示
;blank=0    ; 是否新窗口打开
;display=1    ; 是否显示(默认)，若0则表示该菜单不在前端显示
type=1    ; 类型 0-分组 1-菜单
application='app-perseus-collect'    ; 应用-前端参数
name=TemplateManage    ; 标识-前端参数
extra=    ; 扩展-前端参数

[6075003]
id=6075003    ; 菜单ID
title='主机管理'    ; 菜单名称
pid=6075000    ; 菜单父级ID
icon=''    ; 菜单图标
sort=101    ; 菜单排序
;module=zapi    ; 模块名(可不填写)。默认读取当前模块
;description=''    ; 描述内容
;flag=    ; 菜单标识，配合前端页面跨模块跳转焦点标识
;url=    ; 菜单地址，前端兼容使用(默认空)
;status=1    ; 是否启用(默认启用)，启用的菜单才会在web展示
;blank=0    ; 是否新窗口打开
;display=1    ; 是否显示(默认)，若0则表示该菜单不在前端显示
type=1    ; 类型 0-分组 1-菜单
application='app-perseus-collect'    ; 应用-前端参数
name=HostManage    ; 标识-前端参数
extra=    ; 扩展-前端参数

[6075004]
id=6075004    ; 菜单ID
title='代理管理'    ; 菜单名称
pid=6075000    ; 菜单父级ID
icon=''    ; 菜单图标
sort=101    ; 菜单排序
;module=zapi    ; 模块名(可不填写)。默认读取当前模块
;description=''    ; 描述内容
;flag=    ; 菜单标识，配合前端页面跨模块跳转焦点标识
;url=    ; 菜单地址，前端兼容使用(默认空)
status=0    ; 是否启用(默认启用)，启用的菜单才会在web展示
;blank=0    ; 是否新窗口打开
;display=1    ; 是否显示(默认)，若0则表示该菜单不在前端显示
type=1    ; 类型 0-分组 1-菜单
application='app-perseus-collect'    ; 应用-前端参数
name=ProxyManage    ; 标识-前端参数
extra=    ; 扩展-前端参数

[6075005]
id=6075005    ; 菜单ID
title='脚本管理'    ; 菜单名称
pid=6075000    ; 菜单父级ID
icon=''    ; 菜单图标
sort=101    ; 菜单排序
;module=zapi    ; 模块名(可不填写)。默认读取当前模块
;description=''    ; 描述内容
;flag=    ; 菜单标识，配合前端页面跨模块跳转焦点标识
;url=    ; 菜单地址，前端兼容使用(默认空)
;status=1    ; 是否启用(默认启用)，启用的菜单才会在web展示
;blank=0    ; 是否新窗口打开
;display=1    ; 是否显示(默认)，若0则表示该菜单不在前端显示
type=1    ; 类型 0-分组 1-菜单
application='app-perseus-collect'    ; 应用-前端参数
name=ScriptManage    ; 标识-前端参数
extra=    ; 扩展-前端参数

[6075006]
id=6075006    ; 菜单ID
title='常规设置'    ; 菜单名称
pid=6075000    ; 菜单父级ID
icon=''    ; 菜单图标
sort=101    ; 菜单排序
;module=zapi    ; 模块名(可不填写)。默认读取当前模块
;description=''    ; 描述内容
;flag=    ; 菜单标识，配合前端页面跨模块跳转焦点标识
;url=    ; 菜单地址，前端兼容使用(默认空)
;status=1    ; 是否启用(默认启用)，启用的菜单才会在web展示
;blank=0    ; 是否新窗口打开
;display=1    ; 是否显示(默认)，若0则表示该菜单不在前端显示
type=1    ; 类型 0-分组 1-菜单
application='app-perseus-collect'    ; 应用-前端参数
name=GeneralSettings    ; 标识-前端参数
extra=    ; 扩展-前端参数

