; zapi 模块权限配置数据
; 该文件无需手动添加，
; 1、请在GUI页面`/dev/power/index`下建立数据
; 2、执行`php bin/manager module/build-menu zapi`，即可自动生成
; 注意事项
; 1、权限数据依赖菜单
; 1、每个菜单ID是唯一标识，模块标识+4位，该模块菜单范围60750000~60759999 (10000个)
;    例如: 若是产品级别，则是60750000，非产品级别则60750001开始递增
; 2、若权限废弃，已经使用过的ID不可以重复使用
; 3、以下为用属性，更多属性请查看表`lw_auth_rules`与`lw_auth_rule_items`
[60750000] ;
id=60750000
name='Perseus采集'
menu_id=6075000
is_site=1    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/* ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750001] ;
id=60750001
name='概况'
menu_id=6075001
is_site=1    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/site/info ; 主路由放首个
routes[1]=/zapi/notify/*
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750002] ;
id=60750002
name='模板管理'
menu_id=6075002
is_site=1    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template/* ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750003] ;
id=60750003
name='新增模板'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template/create ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750004] ;
id=60750004
name='编辑模板'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template/update ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750005] ;
id=60750005
name='删除模板'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template/delete ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750006] ;
id=60750006
name='主机管理'
menu_id=6075003
is_site=1    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host/* ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750007] ;
id=60750007
name='新增主机'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host/create ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750008] ;
id=60750008
name='编辑主机'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host/update ; 主路由放首个
routes[1]=/zapi/host/monitor
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750009] ;
id=60750009
name='代理管理'
menu_id=6075004
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/proxy/* ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
status=0    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750010] ;
id=60750010
name='新增代理'
menu_id=6075004
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/proxy/create ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
status=0    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750011] ;
id=60750011
name='编辑代理'
menu_id=6075004
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/proxy/update ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
status=0    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750012] ;
id=60750012
name='删除代理'
menu_id=6075004
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/proxy/delete ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
status=0    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750013] ;
id=60750013
name='脚本管理'
menu_id=6075005
is_site=1    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/script/* ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750014] ;
id=60750014
name='新增脚本'
menu_id=6075005
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/script/create ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750015] ;
id=60750015
name='编辑脚本'
menu_id=6075005
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/script/update ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750016] ;
id=60750016
name='删除脚本'
menu_id=6075005
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/script/delete ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750017] ;
id=60750017
name='常规设置'
menu_id=6075006
is_site=1    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/general-setting/* ; 主路由放首个
routes[1]=/zapi/global-macro/*
routes[2]=/zapi/autoreg/*
routes[3]=/zapi/regexp/*
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750018] ;
id=60750018
name=状态配置
menu_id=6075001
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/notify/setting ; 主路由放首个
sort=1    ; 排序字段
;description=    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块


[60750019] ;
id=60750019
name=删除主机
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host/delete ; 主路由放首个
sort=1    ; 排序字段
;description=    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750020] ;
id=60750020
name='创建监控项'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template-item/create ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750021] ;
id=60750021
name='更新监控项'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template-item/update ; 主路由放首个
routes[1]=/zapi/template-item/batch-update
routes[2]=/zapi/template-item/set-status
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750022] ;
id=60750022
name='删除监控项'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template-item/delete ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750023] ;
id=60750023
name='创建监控项原型'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template-item/create-prototype ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750024] ;
id=60750024
name='更新监控项原型'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template-item/update-prototype ; 主路由放首个
routes[1]=/zapi/template-item/batch-update-prototype
routes[2]=/zapi/template-item/set-prototype-status
routes[3]=/zapi/template-item/set-discover-status
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750025] ;
id=60750025
name='删除监控项原型'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template-item/delete-prototype ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750026] ;
id=60750026
name='监控项测试'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template-item/test ; 主路由放首个
routes[1]=/zapi/template-item/test-form
routes[2]=/zapi/template-item/test-get-value
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750028] ;
id=60750028
name='创建监控项'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host-item/create ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750029] ;
id=60750029
name='更新监控项'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host-item/update ; 主路由放首个
routes[1]=/zapi/host-item/batch-update
routes[2]=/zapi/host-item/set-status
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750030] ;
id=60750030
name='删除监控项'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host-item/delete ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750031] ;
id=60750031
name='创建监控项原型'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host-item/create-prototype ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750032] ;
id=60750032
name='更新监控项原型'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host-item/update-prototype ; 主路由放首个
routes[1]=/zapi/host-item/batch-update-prototype
routes[2]=/zapi/host-item/set-prototype-status
routes[3]=/zapi/host-item/set-discover-status
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750033] ;
id=60750033
name='删除监控项原型'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host-item/delete-prototype ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750034] ;
id=60750034
name='监控项测试'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host-item/test ; 主路由放首个
routes[1]=/zapi/host-item/test-form
routes[2]=/zapi/host-item/test-get-value
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750035] ;
id=60750035
name='监控项执行'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host-item/check-now ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750036] ;
id=60750036
name='创建触发器'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template-trigger/create ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750037] ;
id=60750037
name='更新触发器'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template-trigger/update ; 主路由放首个
routes[1]=/zapi/template-trigger/set-status
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750038] ;
id=60750038
name='删除触发器'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template-trigger/delete ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750039] ;
id=60750039
name='创建触发器原型'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template-trigger/create-prototype ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750040] ;
id=60750040
name='更新触发器原型'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template-trigger/update-prototype ; 主路由放首个
routes[1]=/zapi/template-trigger/set-prototype-status
routes[2]=/zapi/template-trigger/set-discover-status
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750041] ;
id=60750041
name='删除触发器原型'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template-trigger/delete-prototype ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750042] ;
id=60750042
name='创建触发器'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host-trigger/create ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750043] ;
id=60750043
name='更新触发器'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host-trigger/update ; 主路由放首个
routes[1]=/zapi/host-trigger/set-status
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750044] ;
id=60750044
name='删除触发器'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host-trigger/delete ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750045] ;
id=60750045
name='创建触发器原型'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host-trigger/create-prototype ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750046] ;
id=60750046
name='更新触发器原型'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host-trigger/update-prototype ; 主路由放首个
routes[1]=/zapi/host-trigger/set-prototype-status
routes[2]=/zapi/host-trigger/set-discover-status
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750047] ;
id=60750047
name='删除触发器原型'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host-trigger/delete-prototype ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750048] ;
id=60750048
name='创建自动发现'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template-discover-rule/create ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750049] ;
id=60750049
name='更新自动发现'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template-discover-rule/update ; 主路由放首个
routes[1]=/zapi/template-discover-rule/set-status
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750050] ;
id=60750050
name='删除自动发现'
menu_id=6075002
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/template-discover-rule/delete ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750051] ;
id=60750051
name='创建自动发现'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host-discover-rule/create ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750052] ;
id=60750052
name='更新自动发现'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host-discover-rule/update ; 主路由放首个
routes[1]=/zapi/host-discover-rule/set-status
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块

[60750053] ;
id=60750053
name='删除自动发现'
menu_id=6075003
is_site=0    ; 是否为站点权限，1: 是，0: 否（默认）
routes[0]=/zapi/host-discover-rule/delete ; 主路由放首个
sort=1    ; 排序字段
;description=''    ; 描述
;status=1    ; 是否启用(默认启用)，启用的权限才会在web展示
;display=1    ; 是否显示，若0则表示该权限已经(软)删除，闲置
;module=zapi    ; 模块名(可不填写)。默认读取当前模块
