; -- 国际化翻译 --
; 注意: 此文件通过自定义函数[parse_ini()]加载, 仅仅过滤首行`#`和`;`, 内容无需用引号包含
; 示例: name = Name
Perseus采集 = Perseus
概况 = Overview
模板管理 = Template Management
新增模板 = Add Template
编辑模板 = Edit Template
删除模板 = Del Template
主机管理 = Host Management
脚本管理 = Script Management
常规设置 = General Settings

; 权限
状态配置 = State Setting
新增主机 = Add Host
编辑主机 = Edit Host
代理管理 = Agency Management
新增代理 = Add Proxy
编辑代理 = Edit Proxy
删除代理 = Delete Proxy
新增脚本 = Add Script
编辑脚本 = Edit Script
删除脚本 = Delete Script
删除主机 = Delete Host
创建监控项 = Create Item
更新监控项 = Update Item
删除监控项 = Delete Item
创建监控项原型 = Create Item Prototype
更新监控项原型 = Update Item Prototype
删除监控项原型 = Delete Item Prototype
监控项测试 = Test Item
监控项执行 = Execute Item
创建触发器 = Create Trigger
更新触发器 = Update Trigger
删除触发器 = Delete Trigger
创建触发器原型 = Create Trigger Prototype
更新触发器原型 = Update Trigger Prototype
删除触发器原型 = Delete Trigger Prototype
创建自动发现 = Create Discovery
更新自动发现 = Update Discovery
删除自动发现 = Delete Discovery