#Release Time
release_time = 2025-11-06

#Add Some Features
[feature]
1 = [Perseus] Host Management: Added batch execution function for monitoring items.
2 = [Perseus] Host Management: Added support for adding inherited macros when editing a host.
3 = [Perseus] Template Management: Added batch update function for monitoring item lists.
4 = [Perseus] Template Management: Monitoring items now support selecting custom time intervals.
5 = [Perseus] Template Management: Added clone function to the template management list.
6 = [Perseus] Template/Host Management: Added alarm search function to monitoring item lists.
7 = [Perseus] Template/Host Management: Added expression addition function when creating new triggers.
8 = [Perseus] Template/Host Management: Added clone function for monitoring items, monitoring item prototypes, triggers, and trigger prototypes.
9 = [Perseus] Credential Management: Added import function that supports importing multiple SSH credentials or SNMP community names under one rule.
10 = [Perseus] Discovery Management: Optimized scan list function and added a failed scan list.

#Fix Some Bugs
[fix]
1 = [Perseus] Template Management: Fixed issue where switching monitoring item types cleared metric classification data.
