#Release Time
release_time = 2025-09-19

#Add Some Features
[feature]
1 = [Perseus] Host List: Added a new "Business Name" field in the list, supporting click-to-jump to the device requirements page.
2 = [Perseus] Global: Added a global column settings feature.
3 = [Perseus] Host and Template Management: Added menu permissions for editing, adding, and deleting functions such as monitoring items, triggers, and auto-discovery.

#Fix Some Bugs
[fix]
1 = [Perseus] Template Management: Fixed the issue where TrueNAS template import failed because preprocessing macro values could not be imported.
