#Release Time
release_time = 2025-09-04

#Add Some Features
[feature]
1 = [Perseus] Host List: Manual Agent installation drawer page supports adding multiple custom curl addresses.
2 = [Perseus] Host Management: Added [Execute Now] function to the automatic discovery rule drawer page.
3 = [Perseus] Template Management: Template import adapted to import YAML format templates.

#Fix Some Bugs
[fix]
1 = [Perseus] Host Management: Enable/disable not effective.
2 = [Perseus] Template Management: Testing uncreated monitoring items prompts missing itemid.
3 = [Perseus] Host Management: Proxy in test did not retrieve the proxy name.
4 = [Perseus] Host List: Non-admin users without monitoring modules receive no-permission prompt when accessing host management.
