<?php

namespace app\customs\zapi\common\validators\base;

use app\customs\zapi\common\helpers\MacroHelper;
use app\customs\zapi\common\validators\CuidsValidator;
use app\customs\zapi\common\validators\IdsValidator;
use app\customs\zapi\common\validators\Ints32Validator;
use app\customs\zapi\common\validators\ObjectsValidator;
use app\customs\zapi\common\validators\UserMacrosValidator;
use app\customs\zapi\common\validators\Utf8StringsValidator;
use yii\base\Model;
use yii\base\NotSupportedException;
use yii\validators\Validator;

/**
 * Class BaseZValidator
 * @package app\customs\zapi\common\validators\base
 */
class BaseZValidator extends Validator
{
    /**
     * @var string
     */
    const LIST_FLAG = '<list>';

    /**
     * @var int in 值为自定义
     */
    const IN_TYPE_CUSTOM = 0;

    /**
     * @var int in 值为数字
     */
    const IN_TYPE_NUMBER = 1;

    /**
     * @var int in 值为字符串
     */
    const IN_TYPE_STRING = 2;

    /**
     * @var int
     */
    protected $inType = self::IN_TYPE_STRING;

    /**
     * @var bool 不管属性是否为空都验证
     */
    public $skipOnEmpty = false;

    /**
     * @var string
     */
    public $flags = 0x00;

    /**
     * @var mixed
     */
    public $default = null;

    /**
     * 替换当前属性名，并把前属性值置空
     * @var string
     */
    public $replacement = '';

    /**
     * 根据对象的其他属性，为当前属性赋值
     * @var null|string
     */
    public $dataSource = null;

    /**
     * .e.g
     * ['id']、[['name', type]]、['id', ['name', type]]
     * @var array
     */
    public $uniq = [];

    /**
     * @var array
     */
    public $uniq_by_values = [];

    /**
     * @var array
     */
    protected $_path = [];


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (property_exists($this, 'in') && $this->in != '' && !is_array($this->in) && $this->inType != self::IN_TYPE_CUSTOM) {
            $this->in = self::unescapeInRule((string)$this->in);
            if ($this->inType == self::IN_TYPE_NUMBER) {
                $this->in = array_map(function ($v) {
                    if (stripos($v, ':') !== false) {
                        $arr = explode(':', $v);
                        return [floatval($arr[0]), floatval($arr[1]) ?? 0];
                    }
                    return floatval($v);
                }, $this->in);
            }
        }
    }

    /**
     * @param Model $model
     * @param string $attribute
     * @return bool
     * @throws NotSupportedException
     */
    public function validateAttribute($model, $attribute): bool
    {
        if ($model->$attribute === null && $this->default !== null) {
            $model->$attribute = $this->default;
        }
        if ($model->$attribute === null) {
            if (($this->flags & API_REQUIRED)) {
                $this->setError($model, $attribute, t('zapi', 'the parameter "{parameter}" is missing', ['parameter' => $attribute]));
                return false;
            }
            return true;
        }
        if ($model->$attribute === null && !empty($this->dataSource) && property_exists($this, $this->replacement)) {
            $model->$attribute = $model->{$this->replacement};
        }
        if (method_exists($this, 'validateModelValue')) {
            $result = $this->validateModelValue($model, $attribute);
        } else {
            $result = $this->validateValue($model->$attribute);
        }
        if (!empty($result)) {
            $this->setError($model, $attribute, $result[0]);
            return false;
        }
        if (!empty($this->replacement)) {
            if (property_exists($this, $this->replacement) && $model->{$this->replacement} === null) {
                $model->{$this->replacement} = $model->$attribute;
                unset($model->$attribute);
            }
            $this->setError($model, $attribute, t('zapi', 'Deprecated parameter "{attribute}" cannot be used with "{parameter}".', ['attribute' => $attribute, 'parameter' => $this->replacement]));
            return false;
        }
        return $this->checkUnique($model, $attribute);
    }

    protected function setError($model, $attribute, $error)
    {
        if (stripos($error, t('zapi', 'Invalid parameter')) === false) {
            $path = $this->_path ? implode('/', $this->_path) : $attribute;
            $this->addError($model, $attribute, t('zapi', 'Invalid parameter {attribute}, {error}', ['attribute' => $path, 'error' => $error]));
        } else {
            $this->addError($model, $attribute, $error);
        }
    }

    /**
     * @param array $path
     */
    public function setPath(array $path)
    {
        $this->_path = $path;
    }

    /**
     * @return array
     */
    public function getPath(): array
    {
        return $this->_path;
    }

    /**
     * @param $model
     * @param $attribute
     * @return bool
     */
    protected function checkUnique($model, $attribute): bool
    {
        $type = get_class($this);
        switch ($type) {
            case IdsValidator::class:
            case Utf8StringsValidator::class:
            case Ints32Validator::class:
            case CuidsValidator::class:
            case UserMacrosValidator::class:
                return $this->checkStringsUnique($model, $attribute);
            case ObjectsValidator::class:
                return $this->checkObjectsUnique($model, $attribute);
        }
        return true;
    }

    /**
     * @param $model
     * @param $attribute
     * @return bool
     */
    protected function checkStringsUnique($model, $attribute): bool
    {
        $data = $model->$attribute;
        if (!empty($this->uniq) && $data !== null) {
            $uniq = [];
            foreach ($data as $index => $value) {
                $uniq_value = $this instanceof UserMacrosValidator ? MacroHelper::trimMacro($value) : $value;
                if (array_key_exists($uniq_value, $uniq)) {
                    $error = t('zapi', 'value {value} already exists', ['value' => '(' . $value . ')']);
                    $this->setError($model, $attribute, $error);
                    return false;
                }
                $uniq[$uniq_value] = true;
            }
        }
        return true;
    }

    /**
     * @param $model
     * @param $attribute
     * @return bool
     */
    protected function checkObjectsUnique($model, $attribute): bool
    {
        /** @var ObjectsValidator $this */
        $data = $model->$attribute;
        if (!empty($this->uniq) && !empty($data)) {
            $fields = $this->fields;
            foreach ($this->uniq as $fieldNames) {
                $fieldNames = (array)$fieldNames;
                $uniq = [];
                foreach ($data as $index => $object) {
                    if (is_object($object)) {
                        $attributes = get_object_vars($object);
                    } else {
                        $attributes = array_keys($object);
                    }
                    $_uniq = &$uniq;
                    $objectValues = [];
                    $level = 1;
                    foreach ($fieldNames as $fieldName) {
                        if (!in_array($fieldName, $attributes)) {
                            break;
                        }
                        $objectValues[] = $object[$fieldName];
                        $fileRule = $fields[$fieldName];
                        $validator = $fileRule['validator'] ?? current($fileRule);
                        $objectValue = ($validator == UserMacrosValidator::class) ? MacroHelper::trimMacro($object[$fieldName]) : $object[$fieldName];
                        if ($level < count($fieldNames)) {
                            if (!array_key_exists($objectValue, $_uniq)) {
                                $_uniq[$objectValue] = [];
                            }
                            $_uniq = &$_uniq[$objectValue];
                        } else {
                            if (array_key_exists($objectValue, $_uniq)) {
                                $error = t('zapi', 'value {value} already exists', ['value' => '(' . implode(', ', $fieldNames) . ')=(' . implode(', ', $objectValues) . ')']);
                                $this->setError($model, $attribute, $error);
                                return false;
                            }
                            $_uniq[$objectValue] = true;
                        }
                        $level++;
                    }
                }
            }
        }

        if (!empty($this->uniq_by_values) && !empty($data)) {
            $fields = $this->fields;
            foreach ($this->uniq_by_values as $fieldValues) {
                $uniq = [];
                $_uniques = [&$uniq];
                foreach ($data as $index => $object) {
                    if (is_object($object)) {
                        $attributes = get_object_vars($object);
                    } else {
                        $attributes = array_keys($object);
                    }
                    $level = 1;
                    foreach ($fieldValues as $fieldName => $values) {
                        if (!in_array($fieldName, $attributes)) {
                            $_uniques = [&$uniq];
                            break;
                        }
                        $objectValues[] = $object[$fieldName];
                        $fileRule = $fields[$fieldName];
                        $validator = $fileRule['validator'] ?? current($fileRule);
                        $objectValue = ($validator == UserMacrosValidator::class) ? MacroHelper::trimMacro($object[$fieldName]) : $object[$fieldName];
                        if (!in_array($objectValue, $values)) {
                            $_uniques = [&$uniq];
                            break;
                        }
                        if ($level < count($fieldValues)) {
                            $__uniques = [];
                            foreach ($_uniques as &$_uniq) {
                                foreach ($values as $value) {
                                    if (!array_key_exists($value, $_uniq)) {
                                        $_uniq[$value] = [];
                                    }

                                    $__uniques[] = &$_uniq[$value];
                                }
                            }
                            unset($_uniq);
                            $_uniques = $__uniques;
                        } else {
                            foreach ($_uniques as &$_uniq) {
                                foreach ($values as $value) {
                                    if (array_key_exists($value, $_uniq)) {
                                        $combinations = array_map(static function (array $values): string {
                                            return '(' . implode(', ', $values) . ')';
                                        }, $fieldValues);

                                        $error = t('zapi', 'only one object can exist within the combinations of {value}', ['value' => '(' . implode(', ', array_keys($fieldValues)) . ')=(' . implode(', ', $combinations) . ')']);
                                        $this->setError($model, $attribute, $error);
                                        return false;
                                    }
                                    $_uniq[$value] = true;
                                }
                            }
                            unset($_uniq);
                            $_uniques = [&$uniq];
                        }
                        $level++;
                    }
                }
            }
        }
        return true;
    }

    /**
     * @param $err
     * @param array $params
     * @return array
     */
    protected function setValueError($err, array $params = []): array
    {
        return [$err, $params];
    }

    /**
     * Returns unescaped array of "in" rules.
     * @param string $in  A comma-delimited character string. For example, 'xml,json' or '\,,.,/'.
     * @return array  An array of "in" rules. For example, ['xml', 'json'] or [',', '.', '/'].
     */
    private static function unescapeInRule(string $in): array
    {
        $result = [];
        $pos = 0;

        do {
            preg_match('/^([^,\\\\]|\\\\[,\\\\])*/', substr($in, $pos), $matches);
            $result[] = strtr($matches[0], ['\\,' => ',', '\\\\' => '\\']);
            $pos += strlen($matches[0]);

            if (!isset($in[$pos])) {
                break;
            }

            $pos++;
        } while (true);
        return $result;
    }

    protected function stringify($value)
    {
        if (is_bool($value)) {
            return $value ? 'true' : 'false';
        } elseif (is_null($value)) {
            return 'null';
        } elseif (is_object($value)) {
            return get_class($value);
        } elseif (is_scalar($value)) {
            return (string)$value;
        } else {
            return gettype($value);
        }
    }
}
